[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"


[project]
name = "androidmonitor-backend"
description = "Change this to a description of your project."
readme = "README.md"
requires-python = ">=3.7"
keywords = ["androidmonitor-backend"]
license = { text = "BSD 3-Clause License" }
classifiers = ["Programming Language :: Python :: 3"]
dynamic = ["dependencies"]
# Change this with the version number bump.
version = "1.0.0"

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

[tool.pylint."MESSAGES CONTROL"]
good-names = [
    "c",
    "i",
    "ok",
    "id",
    "e",
    "f",
    "s3",
    "dt"
]
disable = "too-many-arguments,too-many-locals,fixme"

[tool.mypy]
ignore_missing_imports = true
